language: php

php:
  - 5.6

sudo: false

addons:
  code_climate:
    repo_token:
      secure: "pdpKVNGLlGWYM7135gqkGIWJptqVheRepxZA4dCmt4GaVChnB/RvemP9Y2J2anIEUGn4gBUU5pIxDgCx65AE2NraeRgZlBETK8G3SeycFQygpU2weGUiIVUiFvl6gRwGfeuN/QclkSGuOGe/isn+ZdDj7VX5W6aWcuZ1hoq8K62DHBNwjyw7MAMXdf0+tEYTIclU56f9g8eolsY767QVIbwuQvvFGPhhX3DFYx3ltcnbs3TjAekZiP4vjgB+kxJ7OyjWmbZV2QHZCuIA0ZvqihMdPRXpH59jeIk2Uk11kWBzQ6IMIAdc4GmXgnL27uJ8xT5krHC0BVtNuEAUxDdNOvG8cLsiZ1Wqk7v1cO0s6A2y5Q59OQcTOQ49JnONsfmLlF2qRDehWF6hOE95DKHanckC+svE4ai8UY7HPqll7ZTQQqeZLAu4+DavcAUkjlx2cJZYYur/czmf02QmsFYMXoGl0UfsYtwdf/F01lYnaVGdXQEI7UtQLZVySOy8tFRnCMu6dETF35w5KFUgDovwmhRKf6/jrine2zRSNIl/XaIVEJFXcBO3FYepipAziguP6DcQHlJERoHKMkHXXAl2OFAlBapflkwfAgS5TVWVrP+YdT8gQfd60q+QXS7tTuj4kEpZyjhjjRNOjf7hiHjnRcBSA2k3TMfeDwqvKCxOWqU="

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: phpunit

after_script:
  - vendor/bin/test-reporter
